# Generated by Django 4.1.3 on 2022-11-05 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('lat', models.CharField(max_length=255)),
                ('long', models.CharField(max_length=255)),
                ('mask', models.ImageField(help_text='png mask for the camera', upload_to='')),
                ('orientation', models.CharField(help_text='The angle between the north and the orientation of the camera in degrees', max_length=255)),
                ('max_cap', models.IntegerField()),
                ('current_load', models.IntegerField()),
            ],
        ),
    ]
