# Generated by Django 4.1.3 on 2022-11-05 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='mask',
            field=models.ImageField(help_text='png mask for the camera', upload_to='masks'),
        ),
    ]
