# Generated by Django 4.1.3 on 2022-11-10 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0003_alter_camera_mask'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='address_verbose',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='camera',
            name='name',
            field=models.CharField(default='test', max_length=255),
            preserve_default=False,
        ),
    ]
