# Generated by Django 4.1.3 on 2022-11-10 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0004_camera_address_verbose_camera_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='is_stationary',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
