# Generated by Django 4.1.3 on 2022-11-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cameras', '0005_camera_is_stationary'),
    ]

    operations = [
        migrations.AddField(
            model_name='camera',
            name='area_height',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='camera',
            name='area_width',
            field=models.FloatField(default=0),
        ),
    ]
